#!/usr/bin/env ruby
# frozen_string_literal: true
# exit 1 unless system("git secrets --commit_msg_hook -- \"#{ARGV[0]}\"")

message_file = ARGV[0]
message = File.read(message_file)

pattern = '\A(?:major|minor|patch)-' \
          '(?:feat|fix|docs|style|test|perf|refactor|chore|ci|build|revert)' \
          '(?:\(\w+\)|) '

unless Regexp.new(pattern).match?(message)
  puts <<~TEXT
    [POLICY] フォーマットが正しくありません。
             <semver>-<type>[(<optional>)] <subject>
    semver = major | minor | patch
    type = feat | fix | docs | style | test | perf | refactor | chore | ci | build | revert
    Click here for details: .github/CONTRIBUTING.md
    Your message was:
    #{message}
  TEXT
  exit 1
end

if message.split(/\n/).first.size > 72
  puts <<~TEXT
    [POLICY] Message titleが72文字以上です。
    Your message was:
    #{message}
  TEXT
  exit 1
end
if message.match?(/\A[^\n]+\n[^#\n][^\n]+/)
  puts <<~TEXT
    [POLICY] Message titleの次の行は空白行である必要があります。
  TEXT
  exit 1
end
